---
title: "Análisis de Tickets de Supermercado: Mini Proyecto 2025"
author: |
  <center>
  Ferrer Font, Neus<br>
  Navarro García, Marta<br>
  Rodríguez Simón, Alba<br>
  Aissa Djellouli, Mohammed<br>
  Balbastre Aparisi, Héctor<br>
  Ruiz Ripoll, Joan<br>
  Martinez Torres, Carlos Santiago
  </center>
date: "`r Sys.Date()`"
output:
  html_document:
    echo: true
    number_sections: true
    theme: lumen
    toc: true
  bookdown::pdf_document2:
    toc: true
    toc_depth: 3
    number_sections: true
    figure_caption: "Figura" # Referencias en castellano
    table_caption: "Tabla"
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  html_notebook:
    echo: true
    number_sections: true
    toc: true
  pdf_document: default
  bookdown::html_document2:
    echo: true
    number_sections: true
    theme: spacelab
    toc: true
    figure_caption: "Figura"
    table_caption: "Tabla"
always_allow_html: true
params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
subtitle: "Tratamiento de datos. Grado en Ciencia de Datos - UV"
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---
# Lo que necesitamos para trabajar. 

Instalación de las librerias.
```{r}
#install.packages("pdftools")
```

Importacion de las librerias. 
```{r, warning=FALSE}


# Lista de paquetes que se van a utilizar
paquetes <- c("pdftools", "dplyr", "stringr", "dplyr", "ggplot2", "tidyr", "stringr")

# Función 
instalar_y_cargar <- function(paquetes) {
  nuevos <- paquetes[!(paquetes %in% installed.packages()[,"Package"])]

  if(length(nuevos) != 0) {
    install.packages(nuevos)
    }

  lapply(paquetes, library, character.only = TRUE)
}

instalar_y_cargar(paquetes)
rm(list = ls())
```

```{r}
   # Guardae todos los archivos PDF en la carpeta "data"
archivos_pdf <- list.files(path = "data", pattern = "\\.pdf$", full.names = TRUE)
  
  # Creamos una lista con los productos que van por peso para usarlos como palabras clave.
diccionario_productos <- list(
  Fruta = c("platano", "manz", "pera", "naranja", "kiwi", "mango", "melón", "sandía", "fresa", "uva", "piña", "ciruela", "cereza", "granada", "banana", "mandarina"),
  Verdura = c("lechuga", "tomate", "cebolla", "zanahoria", "pimiento", "calabacín", "pepino", "espinaca", "acelga", "berenjena", "col", "brócoli", "limon", "alcachofa", "habas"),
  Pescado = c("salmón", "merluza", "gamba", "atún", "bacalao", "lubina", "dorada", "anchoa", "boquerón"))

  # Función que clasifica el producto
clasificar_tipo <- function(desc, diccionario) {
  desc <- tolower(desc)  # todo en minúsculas para evitar errores

  for (tipo in names(diccionario)) {
    if (length(diccionario[[tipo]]) == 0) next
    patrones <- paste(diccionario[[tipo]], collapse = "|")
    if (grepl(patrones, desc)) {
      return(tipo)
    }
  }
  return("Unitario")
}

  # Crear un dataframe vacío donde se almacenarán todos los productos de todos los tickets
  compras_totales <- data.frame( Cantidad = numeric(),
                                 Descripcion = character(),
                                 PrecioUnitario = numeric(),
                                 Importe = numeric(),
                                 Tipo = character(),
                                 stringsAsFactors = FALSE
  )
  
  # Procesar cada archivo PDF
  for (n_pdf in archivos_pdf) {
    
    # Extraer el texto del PDF
    t_pdf <- pdf_text(n_pdf)
    
    # Dividir el texto en líneas
    lineas <- strsplit(t_pdf, "\n")[[1]]
    
    # Limpiar y procesar las líneas
    lineas <- trimws(lineas)
    
    # Información del encabezado - Fijo
    Mercadona <- grepl('MERCADONA', lineas[1]) # Verificamos que sea una factura de Mercadona
    if (!Mercadona) next  # Si no es Mercadona, pasar al siguiente archivo
    
    # Dirección, ubicación, teléfono, fecha, hora y datos de la factura
    direccion <- lineas[2]
    ubicacion <- strsplit(lineas[3], split = ' ')[[1]] 
    CP <- ubicacion[1]
    municipio <- ubicacion[2]
    telefono <- str_sub(string = lineas[4], start = -9)
    fecha <- str_sub(string = lineas[5], start = 0, end = 10)  # Fecha (dd-mm-aaaa)
    hora <- str_sub(string = lineas[5], start = 12, end = 16)
    factura <- str_sub(lineas[6], -15)
    factura <- strsplit(factura, split = "-")[[1]]
    id_tienda <- factura[1]
    n_caja <- factura[2]
    id_factura <- factura[3]
    
    # Información de los productos
    indice_encabezado <- grep(paste0("\\b", 'Descripción', "\\b"), lineas, ignore.case = TRUE)
    indice_total <- grep(paste0("\\b", 'TOTAL', "\\b"), lineas, ignore.case = TRUE)
    
    # Verificar que se encuentren las palabras clave 'Descripción' y 'TOTAL'
    if (length(indice_encabezado) == 0 | length(indice_total) == 0) {
      warning(paste("No se encontraron las palabras clave 'Descripción' o 'TOTAL' en el archivo:", n_pdf))
      next  # Saltar al siguiente archivo si no se encuentran las palabras clave, para no procesar datos incompletos o que son incorrectos.
    }
    
    # Extraer las líneas de productos
    productos <- lineas[(indice_encabezado[1] + 1):(indice_total[1] - 1)]
    productos <- str_replace_all(productos, "\\s+", " ")  # Eliminar espacios múltiples
    
    # Crear un dataframe vacío para los productos de esta factura
    compra <- data.frame( Cantidad = numeric(),
                          Descripcion = character(),
                          PrecioUnitario = numeric(),
                          Importe = numeric(),
                          Tipo = character(),
                          stringsAsFactors = FALSE
    )
    
    # Identificar los patrones de los productos
    patron_normal <- "^([0-9]+)\\s(.+?)\\s([0-9]+,[0-9]{2})\\s+([0-9]+,[0-9]{2})$"
    patron_cantidad_1 <- "^1\\s(.+?)\\s+([0-9]+,[0-9]{2})$"
    patron_peso <- "^([0-9]+)\\s(.+)$"
    patron_precio_peso <- "^([0-9,]+)\\s*kg\\s*([0-9,]+)\\s*€/kg\\s*([0-9,]+)$"
  
    # Procesar cada línea de productos
    i <- 1
    while (i <= length(productos)) {
      p <- productos[i]
      
      # Caso normal (cantidad > 1)
      if ((grepl(patron_normal, p)) | (grepl(patron_cantidad_1, p))) {
        if (str_detect(p, patron_normal)) {
          elementos <- str_match(p, patron_normal)[,2:5]
          resultado <- data.frame( cantidad = as.numeric(elementos[1]),
                                    descripcion = elementos[2],
                                    precio_unit = as.numeric(str_replace(elementos[3], ",", ".")),
                                    importe = as.numeric(str_replace(elementos[4], ",", ".")),
                                    tipo = "Unitario",
                                    stringsAsFactors = FALSE )
        }
        else if (str_detect(p, patron_cantidad_1)) {
          elementos <- str_match(p, patron_cantidad_1)[,2:3]
          precio_total <- as.numeric(str_replace(elementos[2], ",", "."))
          resultado <- data.frame( cantidad = 1,
                                    descripcion = elementos[1],
                                    precio_unit = precio_total,
                                    importe = precio_total,
                                    tipo = "Unitario",
                                    stringsAsFactors = FALSE)
        }
        
        # Agregar al data frame compra
        compra <- rbind(compra, resultado)
      }
      
      # Caso de productos por peso
      else if (str_detect(p, patron_peso)) {
        elemento1 <- str_match(p, patron_peso)[,3]
        
        # Verificar que existe siguiente línea
        if (i + 1 <= length(productos)) {
          i <- i + 1  # Salto para leer la siguiente línea
          peso <- productos[i]
          elemento2 <- str_match(peso, patron_precio_peso)[2:4]
          resultado <- data.frame( cantidad = elemento2[1],
                                    descripcion = elemento1,
                                    precio_unit = as.numeric(str_replace(elemento2[2], ",", ".")),
                                    importe = as.numeric(str_replace(elemento2[3], ",", ".")),
                                    tipo = clasificar_tipo(elemento1, diccionario_productos),
                                    stringsAsFactors = FALSE )
         

          # Agregar al data frame compra
          compra <- rbind(compra, resultado)
        }
      }
      i <- i + 1
    }
    
    # Agregar los productos de esta factura al dataframe global
    compras_totales <- rbind(compras_totales, compra)
  }
  
  # Ver el dataframe final con todas las compras
  compras_totales
  
```